Iris Flower Classification Project

In [20]:
#Step-1:- Import Necessary libraries 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
import numpy as np


#Step-2:- load the dataset of iris flower
data=load_iris()
#print(data)
x=data.data
print(x[:30])
y=data.target
print(y[:30])

print('\nFeature Names:- ',data.feature_names)
print("\nTarget Names:- ",data.target_names)

#Step-3:-  Split the data into training and testing data 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Step-4:- Create the model and train the model by providing trained data
model=LogisticRegression(max_iter=200)
print(model)
model.fit(x_train,y_train)

#Step-5:- Predict the result based on tested data 
calculated_test_data=model.predict(x_test)

#Step-6:- Calculate the accuracy to know how good model is trained by comparing calculated data with actual test data
print('\nCalculated data :- ',calculated_test_data)
print("\nActual data:- ",y_test)
accuracy=accuracy_score(calculated_test_data,y_test)
print("\nAccuracy Score:- ",accuracy)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Feature Names:-  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names:-  ['setosa' 'versicolor' 'virginica']
LogisticRegression(max_iter=200)

Calculated data :-  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

Actual data:-  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

Accuracy Score:-  